services:
  - type: web
    name: it-results-db
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: server.py
      - key: DATABASE_URL
        value: sqlite:///:memory: 